import json
from enum import Enum
from db_handler import get_session
from models import JobPosting
from enums import ExperienceLevel, EnglishLevel, ContractType

REQUIRED_FIELDS = ["title", "description", "company"]

# CORS headers configuration
CORS_HEADERS = {
    "Access-Control-Allow-Origin": "http://localhost:3000",
    "Access-Control-Allow-Headers": "Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token",
    "Access-Control-Allow-Methods": "OPTIONS,GET,POST,PUT,DELETE",
    "Access-Control-Allow-Credentials": "true",
    "Access-Control-Max-Age": "86400"  # 24 hours
}

def create_job_posting_handler(event, context):
    # Get a database session from the connection layer
    session = get_session()

    try:
        print("🔍 Event:", event)
        # Verify that the event has a body
        if "body" not in event:
            return {
                "statusCode": 400,
                "headers": CORS_HEADERS,
                "body": json.dumps({"message": "Missing request body"})
            }

        # Parse the body of the event
        try:
            body = json.loads(event["body"]) if isinstance(event["body"], str) else event["body"]
        except json.JSONDecodeError:
            return {
                "statusCode": 400,
                "headers": CORS_HEADERS,
                "body": json.dumps({"message": "Invalid JSON in request body"})
            }

        # Validate required fields
        missing_fields = [field for field in REQUIRED_FIELDS if field not in body]
        if missing_fields:
            return {
                "statusCode": 400,
                "headers": CORS_HEADERS,
                "body": json.dumps({"message": f"Missing fields: {', '.join(missing_fields)}"})
            }

        # Validate description is not empty
        if not body["description"].strip():
            return {
                "statusCode": 400,
                "headers": CORS_HEADERS,
                "body": json.dumps({"message": "Description cannot be empty"})
            }

        # Get user_id from the event
        claims = event.get("requestContext", {}).get("authorizer", {}).get("claims", {})
        user_id = claims.get("sub")

        if not user_id:
            return {
                "statusCode": 401,
                "headers": CORS_HEADERS,
                "body": json.dumps({"message": "Unauthorized - user_id not found"})
            }

        # --- Data Validation ---
        experience_level = body.get("experience_level")
        english_level = body.get("english_level")
        industry_experience = body.get("industry_experience")
        contract_type = body.get("contract_type")
        additional_requirements = body.get("additional_requirements")
        job_location = body.get("job_location")

        if experience_level is not None:
            try:
                ExperienceLevel(experience_level)
            except ValueError:
                return {"statusCode": 400, "headers": CORS_HEADERS,
                        "body": json.dumps({"message": f"Invalid experience level value: {experience_level}"})}

        # --- End of Data Validation ---

        # 2. Create a new JobPosting object using the ORM model
        new_posting = JobPosting(
            created_by_user_id=user_id,
            title=body["title"],
            company=body["company"],
            description=body["description"],
            location=job_location,
            experience_level=experience_level,
            english_level=english_level,
            contract_type=contract_type,
            industry_experience=industry_experience,
            additional_requirements=additional_requirements
        )

        # 3. Add the new object to the database session
        session.add(new_posting)

        # 4. Commit the changes to the database
        session.commit()

        # 5. Get the UUID generated by the database after the commit
        posting_id = str(new_posting.posting_id)

        # Return the job_id as a response
        return {
            "statusCode": 201,  # 201 Created
            "headers": {
                **CORS_HEADERS,
                "Content-Type": "application/json"
            },
            "body": json.dumps({"posting_id": posting_id})
        }

    except Exception as e:
        # Rollback the session in case of any error
        session.rollback()
        print(f"ERROR: Could not create job posting. {e}")
        return {
            "statusCode": 500,
            "headers": CORS_HEADERS,
            "body": json.dumps({"message": f"Internal server error: {str(e)}"})
        }
    finally:
        # Close the session to clean up resources
        session.close()