name: Deploy to AWS Lambda - delete_applications

on:
  push:
    branches:
      - master
      - dev
    paths:
      - 'lambda/delete_applications/**'
  pull_request:
    branches:
      - master
      - dev
    paths:
      - 'lambda/delete_applications/**'
jobs:
  deploy:
    name: deploy_delete_applications
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.NEW_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.NEW_AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      # Step 1: Get the latest published version of the 'orm-layer'
      - name: Get latest layer version
        id: get_layer
        run: |
          LAYER_VERSION=$(aws lambda list-layer-versions \
            --layer-name orm-layer \
            --query "LayerVersions[0].Version" \
            --output text)

          echo "LAYER_VERSION=$LAYER_VERSION" >> $GITHUB_ENV

      # Step 2: Package the lambda handler's code only
      - name: Package Lambda
        run: |
          # Go to the lambda function directory
          cd lambda/delete_applications
          zip -r ../../delete_applications_handler_lambda.zip delete_applications_handler.py

      - name: "Debug: Current directory and files"
        run: |
          echo "Current directory: $(pwd)"
          ls -l

      # Step 3: Update the Lambda function's code
      - name: Update Lambda function code
        run: |
          aws lambda update-function-code \
            --function-name delete_applications \
            --zip-file fileb://delete_applications_handler_lambda.zip

      - name: Wait for function update to complete
        run: |
          aws lambda wait function-updated \
          --function-name delete_applications

      # Step 4: Update the Lambda function's configuration to use the latest layer
      - name: Update Lambda function configuration
        run: |
          LAYER_ARN="arn:aws:lambda:us-east-2:${{ secrets.NEW_AWS_ACCOUNT_ID }}:layer:orm-layer:${{ env.LAYER_VERSION }}"

          if [ "${GITHUB_REF}" = "refs/heads/master" ]; then
            ORIGIN="${{ secrets.ALLOWED_ORIGIN_PROD }}"
          else
            ORIGIN="${{ secrets.ALLOWED_ORIGIN_DEV }}"
          fi

          aws lambda update-function-configuration \
            --function-name delete_applications \
            --layers $LAYER_ARN
            --environment "Variables={ALLOWED_ORIGIN=$ORIGIN}"