name: Deploy Lambda Layer + Function - cv-processor

on:
  push:
    branches:
      - master
      - dev
  pull_request:
    branches:
      - master
      - dev

jobs:
  deploy:
    name: deploy_cv-processor
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install dependencies for layer
        run: |
          mkdir -p lambda/cv_processor/pymupdf_layer/python
          pip install PyMuPDF Pillow -t lambda/cv_processor/pymupdf_layer/python
      
      - name: Zip layer content
        run: |
          cd lambda/cv_processor/pymupdf_layer
          zip -r ../../../pymupdf_layer.zip python      

      - name: Install dependencies and package Lambda for cv-processor
        run: |
          cd lambda/cv_processor
          pip install -r requirements.txt -t python
          cp cv-processor_handler.py python/
          cd python
          zip -r ../../../cv-processor_handler_lambda.zip .

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Publish Lambda Layer version
        id: publish_layer
        run: |
          LAYER_ARN=$(aws lambda publish-layer-version \
            --layer-name pymupdf-layer \
            --description "PyMuPDF and Pillow Layer" \
            --zip-file fileb://pymupdf_layer.zip \
            --compatible-runtimes python3.9 python3.10 python3.11 python3.13 \
            --query 'LayerVersionArn' \
            --output text)
          echo "LAYER_ARN=$LAYER_ARN" >> $GITHUB_ENV

      - name: Update Lambda function code (with retry)
        run: |
          MAX_RETRIES=5
          COUNT=0
          until aws lambda update-function-code --function-name cv-processor --zip-file fileb://cv-processor_handler_lambda.zip || [ $COUNT -eq $MAX_RETRIES ]; do
            echo "Update code failed, retrying in 10 seconds..."
            sleep 10
            COUNT=$((COUNT + 1))
          done

          if [ $COUNT -eq $MAX_RETRIES ]; then
            echo "Failed to update Lambda code after $MAX_RETRIES attempts."
            exit 1
          fi

      - name: Wait for Lambda function to be ready
        run: |
          while true; do
            STATUS=$(aws lambda get-function-configuration --function-name cv-processor --query 'State' --output text)
            if [ "$STATUS" == "Active" ]; then
              break
            fi
            echo "Function state is $STATUS. Waiting 5 seconds..."
            sleep 5
          done

      - name: Update Lambda function configuration with new Layer (with retry)
        run: |
          MAX_RETRIES=5
          COUNT=0
          until aws lambda update-function-configuration --function-name cv-processor --layers $LAYER_ARN || [ $COUNT -eq $MAX_RETRIES ]; do
            echo "Update configuration failed, retrying in 10 seconds..."
            sleep 10
            COUNT=$((COUNT + 1))
          done

          if [ $COUNT -eq $MAX_RETRIES ]; then
            echo "Failed to update Lambda configuration after $MAX_RETRIES attempts."
            exit 1
          fi

      - name: Cleanup generated files
        run: |
          rm -rf lambda/cv_processor/pymupdf_layer
          rm -f pymupdf_layer.zip cv-processor_handler_lambda.zip