name: Deploy to AWS Lambda - get_cvs_analysis_results

on:
  push:
    branches:
      - master
      - dev
    paths:
      - 'get_cvs_analysis_results/**'
  pull_request:
    branches:
      - master
      - dev
    paths:
      - 'get_cvs_analysis_results/**'

jobs:
  deploy:
    name: deploy_get_cvs_analysis_results
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install dependencies and package Lambda for get_cvs_analysis_results
        run: |
          cd lambda/get_cvs_analysis_results
          pip install -r requirements.txt -t python  
          cp get_cvs_analysis_results_handler.py python/ 
          cd python
          zip -r ../../../get_cvs_analysis_results_handler_lambda.zip .

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.NEW_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.NEW_AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: "Debug: Current directory and files"
        run: |
          echo "Current directory: $(pwd)"
          ls -l

      - name: Verify get_cvs_analysis_results_handler_lambda.zip exists
        run: |
          if [ ! -f $(pwd)/get_cvs_analysis_results_handler_lambda.zip ]; then echo "get_cvs_analysis_results_handler_lambda.zip does not exist"; exit 1; fi

      - name: Deploy get_cvs_analysis_results to AWS Lambda
        run: |
          aws lambda update-function-code \
            --function-name get_cvs_analysis_results \
            --zip-file fileb://$(pwd)/get_cvs_analysis_results_handler_lambda.zip
