name: Deploy ORM Lambda Layer

on:
  push:
    branches:
      - master
      - dev
    paths:
      - 'orm_layer/**'
  pull_request:
    branches:
      - master
      - dev
    paths:
      - 'orm_layer/**'

  workflow_dispatch:

jobs:
  deploy-layer:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.NEW_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.NEW_AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Package Lambda Layer
        run: |
          # Set up the Python directory for the layer
          LAYER_PYTHON_DIR="./orm_layer/python"
          mkdir -p $LAYER_PYTHON_DIR

          echo "Installing dependencies into the layer folder..."  
          pip install SQLAlchemy psycopg2-binary -t $LAYER_PYTHON_DIR

          echo "Copying local code to the layer folder..."
          # Corrected paths to copy your code files into the 'python' folder
          cp ./orm_layer/python/db_handler.py $LAYER_PYTHON_DIR/
          cp ./orm_layer/python/enums.py $LAYER_PYTHON_DIR/
          cp ./orm_layer/python/models.py $LAYER_PYTHON_DIR/
          # Copying the sql folder is not necessary for the layer's runtime

          echo "Creating zip file..."  
          cd orm_layer  
          # The zip file now contains both dependencies and your code
          zip -r orm_layer.zip python/

      - name: Deploy Layer to AWS
        run: |  
          aws lambda publish-layer-version \  
            --layer-name orm-layer \  
            --description "A new version of the ORM layer deployed via GitHub Actions" \  
            --zip-file fileb://orm_layer/orm_layer.zip \  
            --compatible-runtimes python3.13 \  
            --region us-east-2