name: Deploy to AWS Lambda - update-job-posting

on:
  push:
    branches:
      - master
      - dev
  pull_request:
    branches:
      - master
      - dev

jobs:
  deploy:
    name: update-job-posting_handler
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install dependencies and package Lambda for update-job-posting_handler
        run: |
          cd lambda/update_job_posting
          pip install -r requirements.txt -t python  
          cp update-job-posting_handler.py python/ 
          cd python
          zip -r ../../../update-job-posting_lambda.zip .

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: "Debug: Current directory and files"
        run: |
          echo "Current directory: $(pwd)"
          ls -l

      - name: Verify update-job-posting_lambda.zip exists
        run: |
          if [ ! -f $(pwd)/update-job-posting_lambda.zip ]; then echo "update-job-posting_lambda.zip does not exist"; exit 1; fi

      - name: Deploy update-job-posting to AWS Lambda
        run: |
          aws lambda update-function-code \
            --function-name update_job_posting \
            --zip-file fileb://$(pwd)/update-job-posting_lambda.zip
