name: Deploy to AWS Lambda - create_job_description

on:
  push:
    branches:
      - master
      - dev
    paths:
      - 'create_job_description/**'
  pull_request:
    branches:
      - master
      - dev
    paths:
      - 'create_job_description/**'

jobs:
  deploy:
    name: deploy_create_job_description
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install dependencies and package Lambda
        run: |
          # Store the root directory path
          ROOT_DIR=$(pwd)

          # Go to the lambda function directory
          cd lambda/create_job_description

          # Create the 'python' directory for the lambda package
          mkdir python

          # Install dependencies inside the 'python' directory
          pip install -r requirements.txt -t python

          # Copy the entire 'python' folder from the ORM layer to the lambda's 'python' folder
          cp -r $ROOT_DIR/orm_layer/python/* python/

          # Now copy the lambda handler code to the 'python' directory
          cp create_job_description_handler.py python/

          # Zip the 'python' directory to create the deployable package
          cd python
          zip -r ../../../create_job_description_handler_lambda.zip .

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.NEW_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.NEW_AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: "Debug: Current directory and files"
        run: |
          echo "Current directory: $(pwd)"
          ls -l

      - name: Verify create_job_description_handler_lambda.zip exists
        run: |
          if [ ! -f $(pwd)/create_job_description_handler_lambda.zip ]; then echo "create_job_description_handler_lambda.zip does not exist"; exit 1; fi

      - name: Deploy create-job-description to AWS Lambda
        run: |
          aws lambda update-function-code \
            --function-name create_job_description \
            --zip-file fileb://$(pwd)/create_job_description_handler_lambda.zip
