name: Deploy to AWS Lambda - delete-analysis-results

on:
  push:
    branches:
      - master
      - dev
  pull_request:
    branches:
      - master
      - dev

jobs:
  deploy:
    name: delete-analysis-results_handler
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install dependencies and package Lambda for delete-analysis-results_handler
        run: |
          cd lambda/delete_analysis_results
          pip install -r requirements.txt -t python  
          cp delete-analysis-results_handler.py python/ 
          cd python
          zip -r ../../../delete-analysis-results_handler_lambda.zip .

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: "Debug: Current directory and files"
        run: |
          echo "Current directory: $(pwd)"
          ls -l

      - name: Verify delete-analysis-results_handler_lambda.zip exists
        run: |
          if [ ! -f $(pwd)/delete-analysis-results_handler_lambda.zip ]; then echo "delete-analysis-results_handler_lambda.zip does not exist"; exit 1; fi

      - name: Deploy delete-analysis-results to AWS Lambda
        run: |
          aws lambda update-function-code \
            --function-name delete_analysis_results \
            --zip-file fileb://$(pwd)/delete-analysis-results_handler_lambda.zip
