name: Deploy to AWS Lambda - get_recruiter_job_postings

on:
  push:
    branches:
      - master
      - dev
  pull_request:
    branches:
      - master
      - dev

jobs:
  deploy:
    name: deploy_get_recruiter_job_postings
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install dependencies and package Lambda for get_recruiter_job_postings
        run: |
          cd lambda/get_recruiter_job_postings
          pip install -r requirements.txt -t python  
          cp get_recruiter_job_postings_handler.py python/ 
          cd python
          zip -r ../../../get_recruiter_job_postings_handler_lambda.zip .

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.NEW_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.NEW_AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: "Debug: Current directory and files"
        run: |
          echo "Current directory: $(pwd)"
          ls -l

      - name: Verify get_recruiter_job_postings_handler_lambda.zip exists
        run: |
          if [ ! -f $(pwd)/get_recruiter_job_postings_handler_lambda.zip ]; then echo "get_recruiter_job_postings_handler_lambda.zip does not exist"; exit 1; fi

      - name: Deploy get_recruiter_job_postings to AWS Lambda
        run: |
          aws lambda update-function-code \
            --function-name get_recruiter_job_postings \
            --zip-file fileb://$(pwd)/get_recruiter_job_postings_handler_lambda.zip
